version: '3.1'
services:
    dynasty_ws:
        image: tanphamvan/dynasty_ws
        container_name: dynasty_ws
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-development
        ports:
            - 2002:2002
        environment:
            - PORT=2002
            - MONGO_URL=mongodb+srv://dynasty:dynasty123@cluster0.tqwu0qn.mongodb.net/Dynasty?retryWrites=true&w=majority
            - NODE_ENV=production
            - FRONTEND_URL=http://localhost:1311
            - BASE_URL=http://localhost
            - JWT_ACCESS_KEY=JWT_ACCESS_KEY
            - JWT_REFRESH_KEY=JWT_REFRESH_KEY
        networks:
            - dynasty_network
networks:
    dynasty_network:
        external: true
