version: '3.1'
services:
    dynasty_ws:
        image: tanphamvan/dynasty_ws
        container_name: dynasty_ws
        restart: always
        build:
            context: .
            dockerfile: Dockerfile-development
        ports:
            - 1009:1009
        depends_on:
            - mongo_db
            - mongo_express
        env_file:
            - .env.development
        networks:
            - dynasty_network

    mongo_express:
        image: mongo-express
        container_name: mongodb-express
        depends_on:
            - mongo_db
        env_file:
            - .env
        ports:
            - "8888:8081"
        networks:
            - dynasty_network

    mongo_db:
        image: mongo
        container_name: mongodb
        env_file:
            - .env
        ports:
            - 27017:27017
        networks:
            - dynasty_network

networks:
    dynasty_network:
        external: true
